version: '3.8'

services:
  api:
    container_name: weather-flask-api
    build: .
    command: gunicorn --bind 0.0.0.0:9090 manage:app
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - ./migrations/versions:/usr/src/app/migrations/versions
    depends_on:
      - db
  db:
    container_name: weather-pg-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=weather
      - POSTGRES_PASSWORD=weather
      - POSTGRES_DB=weather
    ports:
      - "54320:5432"
volumes:
  postgres_data: