"""setting point name as unique

Revision ID: a2c822db9141
Revises: f096f9c8c133
Create Date: 2023-04-15 15:44:10.016204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c822db9141'
down_revision = 'f096f9c8c133'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'point', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point', type_='unique')
    # ### end Alembic commands ###
